---
# file: roles/glusterfs/tasks/main.yml
- name: add nodes to file /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}    {{ item.name }}"
  with_items:
    - "{{ nodes }}"

- name: install glusterfs-server and start service glusterd
  package:
    name: glusterfs-server
    state: present

- name: enable and start service glusterd
  service:
    name: glusterd
    enabled: yes
    state: restarted

- name: create brick directory
  file:
    path: "{{ brick_dir }}"
    state: directory
    mode: '0775'

- name: create gluster volume
  gluster_volume:
    state: present
    name: "{{ gluster_vol }}"
    bricks: "{{ brick_dir }}"
    replicas: "{{ gluster_replicas }}"
    arbiters: "{{ gluster_arbiters }}"
    rebalance: no
    cluster: "{{ nodes | map(attribute='name') | join(',')}}"
    force: true
  run_once: true

- name: start gluster volume
  gluster_volume:
    state: started
    name: "{{ gluster_vol }}"

- name: create mount directory
  file:
    path: "{{ mount_dir }}"
    state: directory
    mode: '0775'

- name: "mount {{ ansible_hostname }}:/{{ gluster_vol }} to {{ mount_dir }}"
  mount:
    path: "{{ mount_dir }}"
    src: "{{ ansible_hostname }}:/{{ gluster_vol }}"
    fstype: glusterfs
    opts: defaults,_netdev,noauto,x-systemd.automount
    state: mounted