apiVersion: v1
kind: Pod
metadata:
  name: localvolume
spec:
  containers:
  - name: localvolume
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/local"
      name: localvol
  volumes:
  - name: localvol
    persistentVolumeClaim:
      claimName: example-pvc