---
# file: roles/pxeboot/tasks/packages.yml
- name: install tftpd
  package:
    name: tftpd
    state: present

- name: install unzip
  package:
    name: unzip
    state: present

- name: install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: install kpartx
  package:
    name: kpartx
    state: present

- name: install nfs-kernel-server
  package:
    name: nfs-kernel-server
    state: present