---
# file: backup.yml
- hosts: backup
  become: yes
  roles:
    - role: common
      tags: install
    - role: user_config
      tags: 
      - install
      - user_config
    - role: ssh_config
      tags: install
    - role: backup
      tags: backup
    - role: update
      tags: update
    - role: scripts
      tags: scripts