---
# file: lailaps.yml
- hosts: lailaps
  become: yes
  roles:
    - role: common
      tags: install
    - role: user_config
      tags: 
      - install
      - user_config
    - role: upload
      tags:
      - install
      - upload
    - role: update
      tags: update
    - role: scripts
      tags: scripts
    - role: ssh_config
      tags: install