---
# file: roles/update/tasks/os.yml
#ToDo: use chroot at control01
- name: run apt update
  apt:
    update_cache: yes
    autoclean: yes
  become_user: root
  become: yes

- name: run apt full-upgrade
  apt:
    upgrade: full
    autoremove: yes
    force_apt_get: yes
  become_user: root
  become: yes

#- name: install rpi-eeprom
#  apt:
#    name: rpi-eeprom
#    state: present